name: Run Docker Container Daily

on:
  schedule:
    - cron: '* 10 * * *' # IL 12:00

jobs:
  run-container:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run a test command
        run: echo "test 5 minutes"

      - name: Login to Docker Hub (Optional if the image is public)
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Pull Docker Image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/birmanator:latest

      - name: Run Docker Container
        run: |
          docker run -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
                     -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
                     -e REGION=${{ env.REGION }} \
                     -e BUCKET=${{ env.BUCKET }} \
                     ${{ secrets.DOCKERHUB_USERNAME }}/birmanator:latest
